### ISSUE TITLE
Response content must be a string or an object implementing __toString().

### ISSUE THREAD

**Issue by trexanhvn** [boundstate/yii2-importexport#1]
I follow as your instruction, but when I run, it appeared error like this:
    Response content must be a string or an object implementing __toString().

My Controller with actionImport():

```
public function actionImport()
    {
        $model = new Contact();

        if ($model->load(Yii::$app->request->post())) {
            $model->fileImport = UploadedFile::getInstance($model, 'fileImport');
            if ($model->validate()) {
                $reader = new ExcelReader(['destination' => Contact::className()]);
                $reader->import($model->fileImport->tempName);
                if ($reader->getErrors()) {
                    var_dump($reader->getErrors());
                }
            }
            return $model;
        }
        return $this->render('import', [
            'model' => $model
        ]);
    }
```

My Model:

```
public function import($reader, $row, $data)
    {
        if ($row == 0) {
            if ($data != ['Name', 'Company', 'Project', 'Introducer', 'Email', 'Mobile', 'Skype']) {
                $reader->addError($row, 'Invalid headers.');
                return false;
            }
            // Skip header row
            return true;
        }
        $contact = new Contact;

    }
```

I don't know what I implement in the line `//Skip header row`.

**Comment by mikejpeters** [comment]
I think you are getting this error because of the line `return $model;` in `actionImport()`.  With Yii you normally need to return a string (HTML content) from your controller actions, unless you are using something like the RESTful controller that has a different serializer.  You should probably be returning a rendered view.

**Comment by trexanhvn** [comment]
Thanks for your reply,
For first to understand your extension, I will return a string that I debug.
Thanks again.

**Comment by mikejpeters** [comment]
You're welcome
